services:
  saltygamingbot:
    build: .
    container_name: saltygaming-bot
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json
    ports:
      - "8081:8080"  # Changed host port to avoid conflict
