services:
  saltygamingbot:
    build: .
    container_name: saltygaming-bot
    restart: unless-stopped
    networks:
      - docker_network
    volumes:
      - ./config.json:/app/config.json
    ports:
      - "8081:8080"

networks:
  docker_network:
    external: true
