services:
  saltygamingdiscordbot:
    build: .
    container_name: saltygamingdiscordbot
    networks:
      - docker_network
    restart: unless-stopped

networks:
  docker_network:
    external: true