services:
  saltygaming-bot:
    build:
      context: .
    container_name: saltygamingdiscordbot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DB_PASS=${DB_PASS}
      - CONFIG_PATH=${CONFIG_PATH}
    volumes:
      - ${CONFIG_PATH}:/app/config
    restart: unless-stopped
