services:
  saltygamingdiscordbot:
    build: .
    container_name: saltygamingdiscordbot
    environment:
      - DISCORD_TOKEN=your_actual_discord_token
      - MYSQL_HOST=192.168.1.6
      - MYSQL_USER=ark
      - MYSQL_PASSWORD=
      - ARK_DISCORD_DB=ark_discord
      - ARK_ASA_PERMISSIONS_DB=ark_asa_permissions
    networks:
      - docker_network
    restart: unless-stopped

networks:
  docker_network:
    external: true